name: Katalon Studio Execution Example

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # Supaya bisa klik "Run workflow" manual di GitHub

permissions:
  contents: write
  packages: write
  actions: read

jobs:
  katalon-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        # with:
        #   token: ${{ secrets.KATALON_TOKEN }} 
        #   persist-credentials: false

      - name: Run Katalon Studio Project
        uses: katalon-studio/katalon-studio-github-action@v2
        with:
 
          version: 'latest' 
          projectPath: '${{ github.workspace }}'
          args: '-noSplash -browserType="Chrome" -retry=0 -statusDelay=15 -testSuitePath="Test Suites/TS_Login"'
        env:
          KATALON_API_KEY: ${{ secrets.KATALON_TOKEN }}
